---
- name: install keepalived
  ansible.builtin.yum:
    name: keepalived
    state: present
  notify: restart keepalived

- name: copy keepalived
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: restart keepalived

- name: restart keepalived and ensure enable
  ansible.builtin.systemd:
    name: keepalived
    state: restarted
    enabled: true